version: '2'
services:
  web:
    image: gitea/gitea:1.12.6
    volumes:
      - ./src/integration/resources/gitea_data:/data
      - ./src/integration/resources/test_repo:/test_repo
    ports:
      - "3000:3000"
      - "22:22"
    restart: always
